eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/,http://localhost:9001/eureka/
server:
  port: 9005
spring:
  application:
    name: service-feign
feign:
    hystrix:
        enabled: true
# 请求压缩
    compression:
         request:
         response:
             enabled: true
             mime-types: text/html,application/json
             min-request-size: 2048
#日志
logging:
  level: debug

