eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/,http://localhost:9001/eureka/
server:
  port: 9009
spring:
  application:
    name: service-feign
feign:
    hystrix:
        enabled: true