server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true

# docker run --name discovery -p 8761:8761 -t discovery
# docker run --link discovery:8761 -p 9000:9000 -t user
# docker run --link discovery:8761 -p 9001:9001 -t client
# docker build -t xxx .